### ISSUE TITLE
Directory based reverse proxy

### ISSUE THREAD

**Issue by mikafouenski** [Sonarr/Sonarr#2694]
I'm triing to run sonarr(docker) beind a reverse proxy(Traefik).
I'm able to run it like sonarr.example.com but not like example.com/sonarr.

Here is my compose file `docker-compose.yml`

```yaml
version: '3.5'

services:
  traefik:
    image: 'traefik'
    container_name: 'traefik'
    ports:
      - '80:80'
    command:
      - "--logLevel=DEBUG"
      - "--docker"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  sonarr:
    image: 'linuxserver/sonarr'
    container_name: 'sonarr'
    volumes:
      - ./conf:/config
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.port=8989"
      - "traefik.frontend.rule=Path:/sonarr"
```

My `conf/config.xml` look like:

```xml
<Config>
  <LogLevel>Debug</LogLevel>
  <Port>8989</Port>
  <UrlBase>/sonarr</UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>c9ef20bd144c41e6b79cb099c0feb736</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <Branch>master</Branch>
</Config>
```

Launching with `docker-compose up -d`
Accessing via `localhost/sonarr`

Relevant info from browser(firefox) console:
```
Loading failed for the <script> with source “http://localhost/sonarr/polyfills.js?h=lNPw50dpfmIeXiK2IfrqdQ”. sonarr:96
Loading failed for the <script> with source “http://localhost/sonarr/handlebars.runtime.js?h=VR1gUKhkPyiPuEfway9bag”. sonarr:97
Loading failed for the <script> with source “http://localhost/sonarr/templates.js?h=N9lj49+tcOZWnr8t/2P2ww”. sonarr:98
Loading failed for the <script> with source “http://localhost/sonarr/vendor.js?h=fe6fSQ+2JFtQUk7ty3Rvvw”. sonarr:99
Loading failed for the <script> with source “http://localhost/sonarr/main.js?h=ntIxVVg+PaTCDplgIArp7w”.
```

No useful log from traefik nor sonarr.
No useful info in https://github.com/Sonarr/Sonarr/wiki/Reverse-Proxy either...

**Screenshots**

![screenshot from 2018-07-31 15-17-53](https://user-images.githubusercontent.com/11093325/43461901-f4e45a0a-94d4-11e8-8c13-9a076a0426bd.png)

**System Information**

 - Sonarr Version: Docker image `latest` `linuxserver/sonarr@sha256:c98e29a102318fb2f5db779658b9ca4ccdcb097dbb8ad175a48a385e50a74d30`

Is this a configuration error or Sonarr is not able to run under directory based reverse proxy ?

I really like sonarr, nice work,
Mika
