### ISSUE TITLE
Front end UI doesn't seem to update when back end actions take place

### ISSUE THREAD

**Issue by WormChickenWizard** [Sonarr/Sonarr#4629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Buttons such as the refresh button don't seem to respond on the front end. Its been this way since I upgraded to sonarr v3 from v2. I run radarr v3 as well and upgraded from radarr v2 to it. I assume they're architecturally similar. When on the page for any particular movie on radarr, when I hit the "Refresh & Scan" button, the button will change to the dots circling and the rest of the UI will update to reflect any changes if any. Sonarr on the other hand, if I hit the same button for a tv series `/series/anytvseries`, it gets pushed to the back end but if anything changes (like if new tv episodes were found on disk) it won't reflect those changes until I refresh the page. 

One thing that was weird when I was getting the debug and trace logs was the animation for the "Refresh" button the `/system/logs/files` page and the "Save Changes" button `/settings/general` page seemed to be working properly. The "Refresh" button on the `/activity/queue` page does play the dots circling animation when I first navigate to the page but if I actually click it to perform a refresh, it does nothing.

### Expected Behavior

If I were to hit the "Refresh & Scan" button on a tv series page `/series/anytvseries`, once the operation takes place on the backend, the button will change to the "circling dots" animation. Once the operation completes, and if there are any changes made to the series, the UI will update without having to refresh the web page.

### Steps To Reproduce

I'm not entirely sure if starting from sonarr v2 and upgrading to v3 is the culprit, but it did seem to take longer for sonarr v3 to come out compared to radarr v3, at least for the linuxserver containers. Heres the docker compose entry that I use:
```yml
version: "3.3"
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    networks:
      plex_default:
        ipv4_address: 172.18.0.2
    ports:
      - 8989:8989
    volumes:
      - /home/docker/sonarr/config:/config
      - /path/to/shows:/path/to/shows
    environment:
      - TZ=America/Chicago
      - PGID=1000
      - PUID=1000
networks:
  plex_default:
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
```

### Environment

```markdown
- OS: linuxserver docker container, debian 10 host
- Sonarr: 3.0.6.1265
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave v1.28.105 and Firefox 91.0
```

### What branch are you running?

Main

### Anything else?

Trace logs. Password is `sonarr`: https://pastebin.com/Md7gER7W
One thing to note is I am using rclone for my media which can have a lack of responsiveness. I double checked in radarr to make sure the "Refresh & Scan" button did work over on rclone and it took a couple of seconds for the animation to kick in but it did work. Another behavior to mention that radarr exhibits but not sonarr. When I perform operations like Refresh & Scan, I get the status messages in the bottom left on radarr but not on sonarr.
