### ISSUE TITLE
Correctly parse the term "BDRemux" as "Remux-1080p" Quality

### ISSUE THREAD

**Issue by Raventhicc** [Sonarr/Sonarr#5094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, the term `BDRemux` is not recognized and so the quality defaults to `HDTV-1080p`
`BDRemux` is a common term used for Anime Remuxes and so support for it should be added.

For example, using `api/v3/parse?title=Kaguya-sama Love is War Season 2 (BDRemux 1080p HEVC FLAC) [Netaro]` this is the result:
```yml
{
  "title": "Kaguya-sama Love is War Season 2 (BDRemux 1080p HEVC FLAC) [Netaro]",
  "parsedEpisodeInfo": {
    "releaseTitle": "Kaguya-sama Love is War Season 2 (BDRemux 1080p HEVC FLAC) [Netaro]",
    "seriesTitle": "Kaguya-sama Love is War",
    "seriesTitleInfo": {
      "title": "Kaguya-sama Love is War",
      "titleWithoutYear": "Kaguya-sama Love is War",
      "year": 0
    },
    "quality": {
      "quality": {
        "id": 9,
        "name": "HDTV-1080p",
        "source": "television",
        "resolution": 1080
      },
```

### Expected Behavior

Correctly recognizing and parsing `BDRemux` in Anime Releases as `Remux-1080p` quality.
Radarr already does this:
```yml
{
  "title": "[Vodes] Made in Abyss - Dawn of the Deep Soul (2020) [BDRemux 1080p HEVC Dual-Audio]",
  "parsedMovieInfo": {
    "movieTitles": [
      "Made in Abyss - Dawn of the Deep Soul"
    ],
    "originalTitle": "[Vodes] Made in Abyss - Dawn of the Deep Soul (2020) [BDRemux 1080p HEVC Dual-Audio]",
    "releaseTitle": "[Vodes] Made in Abyss - Dawn of the Deep Soul (2020) [BDRemux 1080p HEVC Dual-Audio]",
    "simpleReleaseTitle": "A Movie (2020) [BDRemux 1080p HEVC Dual-Audio]",
    "quality": {
      "quality": {
        "id": 30,
        "name": "Remux-1080p",
        "source": "bluray",
        "resolution": 1080,
        "modifier": "remux"
      },
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.8.1507-ls150 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[Logs](https://bin.theindex.moe/?1c655a52be2ac616#GB6EpiX5mbMUcyDX5RB7z6REFnUb2oRdQW4WEzBDv2F1)

### Anything else?

![image](https://user-images.githubusercontent.com/78981416/181087231-9199187a-a0e3-4aac-b931-502729ac5fe3.png)

**Comment by thezoggy** [comment]
bdremux is supported, just 1080p should come **before** not after the source
https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/QualityParser.cs#L67

so just bad release name...

**Comment by Raventhicc** [comment]
That's still an issue because there's a lot of releases that put resolution after quality

**Comment by bakerboy448** [comment]
> bdremux is supported, just 1080p should come **before** not after the source: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Parser/QualityParser.cs#L67
> 
> sadly due to how anime p2p are done.. this isnt a one off. so plenty of releases doing resolution after source...

Look closer at the regex. The resolution is not required to be before it.

the issue is BDRemux is prefixed with `[` rather than any of `-. `

**Comment by Raventhicc** [comment]
Oh wait, this issue isn't limited to Remux. Here's another title i tested:
```yml
{
  "title": "Kaguya-sama Love is War Season 2 [WEB 1080p HEVC Opus] [Netaro]",
  "parsedEpisodeInfo": {
    "releaseTitle": "Kaguya-sama Love is War Season 2 [WEB 1080p HEVC Opus] [Netaro]",
    "seriesTitle": "Kaguya-sama Love is War",
    "seriesTitleInfo": {
      "title": "Kaguya-sama Love is War",
      "titleWithoutYear": "Kaguya-sama Love is War",
      "year": 0
    },
    "quality": {
      "quality": {
        "id": 9,
        "name": "HDTV-1080p",
        "source": "television",
        "resolution": 1080
      },
```
