### ISSUE TITLE
Expand parsing of v2/v3/etc for Anime

### ISSUE THREAD

**Issue by Raventhicc** [Sonarr/Sonarr#5103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sonarr seems to not recognize revisions unless the version info is right next to the episode number.
`/api/v3/parse?title=BEASTARS - S01E01 v2 - (BD 1080p HEVC FLAC) [Dual Audio] [Group].mkv`:
```yml
      "revision": {
        "version": 1,
        "real": 0,
        "isRepack": false
      }
```
`/api/v3/parse?title=[SubsPlease] BEASTARS - 01 v2 (1080p) [B1F227CF].mkv`:
```yml
      "revision": {
        "version": 1,
        "real": 0,
        "isRepack": false
      }
```

### Expected Behavior

These work:
`/api/v3/parse?title=BEASTARS - S01E01v2 - (BD 1080p HEVC FLAC) [Dual Audio] [Group].mkv`:
```yml
      "revision": {
        "version": 2,
        "real": 0,
        "isRepack": false
      }
```
`/api/v3/parse?title=[SubsPlease] BEASTARS - 01v2 (1080p) [B1F227CF].mkv`:
```yml
      "revision": {
        "version": 2,
        "real": 0,
        "isRepack": false
      }
```
Expected behavior would be correctly identifying revisions regardless of where they are in the filename.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 3.0.8.1507-ls152 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Main

### Trace Logs?

[Logs](https://bin.theindex.moe/?9fe9b9aa078a9d26#4voxVcUpxVvskATySRB2weYHW5UTrgHifCYGGdADnzq6)

### Anything else?

Before Import Name:
[![Before import](https://i.imgur.com/3oAQOas.png "Before import")](https://i.imgur.com/3oAQOas.png "Before import")

After Import Name (version info gets omitted):
[![After Import](https://i.imgur.com/SQ5nzCH.png "After Import")](https://i.imgur.com/SQ5nzCH.png "After Import")

Same thing but with `S01E01v2`:
[![Before Import](https://i.imgur.com/xmNDMOJ.png "Before Import")](https://i.imgur.com/xmNDMOJ.png "Before Import")

[![After Import](https://i.imgur.com/3Zv6VDG.png "After Import")](https://i.imgur.com/3Zv6VDG.png "After Import")
