### ISSUE TITLE
Add a way to configure sonarr without interacting with the web gui or the api

### ISSUE THREAD

**Issue by Laikar** [Sonarr/Sonarr#5138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I am trying to setup an ansible playbook for my home server, and i have found no way to configure sonarr (or any other *arr app) without interacting manually with the webui or manually writing http to post the options to the api.

### Describe the solution you'd like

Ideally, there could be a YAML or similar markup language file or multiple files where we could specify the configuration for sonarr, things such as download clients, indexers, root folders, ui language, profiles etc.

### Describe alternatives you've considered

Someone made [Flemmarr](https://github.com/Flemmarr/Flemmarr), which while can kinda provide what i'm asking, its just a wrapper that turns YAML into web api calls.

### Anything else?

This is a simple YAML mockup of the intended configuration file i would like implemented
  ```yaml
root_folders:
  - name: Main
    path: /storage/library/Series
downloadclient:
    #Displayname of the download client
  - name: qBittorrent
    #Whether the client is enabled or disabled 
    enable: true
    # wht type of client are we actually using qbt/transmission/etc
    profile: qBittorrent
    # Host for the client
    host: qbittorrent
    # Port for the client
    port: 8080
    #credentials for login
    username: user
    password: password
    # and so on, with all the parameters that aren't absolutelly necesary beeing capable of beeing omited, ex
    # the default value is to delete when completed on the gui, so if the key isn't present on the config file, default values would be used,
    # delete_when_completed: true
indexers:
    # display name of the indexer
  - name: Nyaa
    #default profile for the indexer
    profile: nyaa
    # indexer URL
    url: nyaa.example
  
```
