### ISSUE TITLE
VARYG releases are not being parsed properly.

### ISSUE THREAD

**Issue by Ravencentric** [Sonarr/Sonarr#5308]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Release Group gets parsed as `Subs` instead of `VARYG` for multi-sub VARYG releases.
Example:
Nyaa title: `BLUE.LOCK.S01E09.1080p.DSNP.WEB-DL.DDP2.0.H.264-VARYG (Blue Lock, Multi-Subs)`
Filename: `BLUE.LOCK.S01E09.1080p.DSNP.WEB-DL.DDP2.0.H.264-VARYG.mkv`

```yml
{
  "title": "BLUE.LOCK.S01E09.1080p.DSNP.WEB-DL.DDP2.0.H.264-VARYG (Blue Lock, Multi-Subs)",
  "parsedEpisodeInfo": {
    "releaseTitle": "BLUE.LOCK.S01E09.1080p.DSNP.WEB-DL.DDP2.0.H.264-VARYG (Blue Lock, Multi-Subs)",
    "seriesTitle": "BLUE LOCK",
    "seriesTitleInfo": {
      "title": "BLUE LOCK",
      "titleWithoutYear": "BLUE LOCK",
      "year": 0
    },
    "quality": {
      "quality": {
        "id": 3,
        "name": "WEBDL-1080p",
        "source": "web",
        "resolution": 1080
      },
      "revision": {
        "version": 1,
        "real": 0,
        "isRepack": false
      }
    },
    "seasonNumber": 1,
    "episodeNumbers": [
      9
    ],
    "absoluteEpisodeNumbers": [],
    "specialAbsoluteEpisodeNumbers": [],
    "languages": [
      {
        "id": 0,
        "name": "Unknown"
      }
    ],
    "fullSeason": false,
    "isPartialSeason": false,
    "isMultiSeason": false,
    "isSeasonExtra": false,
    "special": false,
    "releaseGroup": "Subs",
    "releaseHash": "",
    "seasonPart": 0,
    "releaseTokens": ".1080p.DSNP.WEB-DL.DDP2.0.H.264-VARYG (Blue Lock, Multi-Subs)",
    "isDaily": false,
    "isAbsoluteNumbering": false,
    "isPossibleSpecialEpisode": false,
    "isPossibleSceneSeasonSpecial": false
  },
  ```

### Expected Behavior

Release Group gets parsed as `VAYRG`.

### Steps To Reproduce

1. Download any multi-sub VARYG release and let Sonarr import it.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 4.0.0.287
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

[Trace Logs](https://privatebin.net/?521fbe1b27755b6c#7UiSG4y1mJ71kFfumCnN1UWr7TMmtXCrKwANauCWpe5Y)
