### ISSUE TITLE
*Arrs crashing/segfaults - mono libclrjit.so

### ISSUE THREAD

**Issue by h1ght** [Sonarr/Sonarr#5375]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When browsing on the arr apps and searching for stuff the process is crashing or adding via api key for ombi e.g.
e.g.
[So Jan 15 12:56:48 2023] Code: 48 c1 e1 20 48 09 c1 48 0f ba e1 24 4b 8d 44 20 08 48 0f 43 c3 8b 30 48 83 c4 18 5b 41 5c 41 5d 41 5e 41 5f 5d e9 54 17 00 00 <41> 0f b6 45 00 83 e0 1f 3c 0f 75 09 43 3b 4c 20 20 77 b3 eb 0f 48
[So Jan 15 12:57:01 2023] traps: .NET Tiered Com[104503] general protection fault ip:7faf18f0ed2c sp:7faf18e0f5a0 error:0 in libclrjit.so[7faf18e60000+1e1000]
[So Jan 15 12:57:01 2023] Radarr[104539]: segfault at 7f84ba4991f0 ip 00007f14bbeced2c sp 00007ffd1f1c09a0 error 4 in libclrjit.so[7f14bbe20000+1e1000]
i watched the codes couple of times and they look the same, nearly all the time. be aware im using debian 11. mono says they didnt tested it as stated on their homepage. before i went into docker i ran them directly on my host using the guide on the arr wiki. i dont have the logs of the older stuff, but when i remember it crashed sometimes. often enough it works just fine. but sometimes it saying "nope". not that important i guess

when im looking up that stuff, it looks like a software bug on mono. ive tested my rams with memtest, swapped the moduls and slots. but it is still the same. mentioned i only get segfaults on *arr/mono.

im using docker-compose on debian 11, doenst matter backports kernel or 5.10.20. 
```
`version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /docker-volumes/sonarr:/config
      - /mnt/lvm-vg01:/data
    ports:
      - 7777:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - /docker-volumes/radarr:/config
      - /mnt/lvm-vg01:/data
    restart: unless-stopped	
    
  prowlarr:
     container_name: prowlarr
     image: lscr.io/linuxserver/prowlarr:develop
     ports:
      - "9696:9696"
     environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Berlin
     volumes:
      - /docker-volumes/prowlarr:/config
     restart: unless-stopped
    
  
  ombi:
    image: lscr.io/linuxserver/ombi:development
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      #- BASE_URL=/ombi #optional
    volumes:
      - /docker-volumes/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ombi.rule=Host(`randomdyndns)"
      - "traefik.http.routers.ombi.tls=true"
      - "traefik.http.routers.ombi.tls.certresolver=letsencrypt"
      - "traefik.http.services.ombi.loadbalancer.server.port=3579"`
```

### Expected Behavior

no segfaults/crashing of the apps.

### Environment

```markdown
- OS: #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1~bpo11+1 (2022-12-19) and 5.10.0-20-amd64
- Sonarr:lscr.io/linuxserver/sonarr:develop
- Docker Install:Docker version 20.10.22, build 3a2c30b
- Using Reverse Proxy:traefik 
- Browser:firefox

Mono JIT compiler version 6.12.0.182 (tarball Tue Jun 14 22:43:31 UTC 2022)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)
```

### What branch are you running?

Main

### Trace Logs?

https://gist.github.com/h1ght/2444fa49cd7bab75c52ce6a3e056c784 
https://gist.github.com/h1ght/9a667967201ade6a58dd9971b98d9178
https://gist.github.com/h1ght/b365a9c993c3ef19f36307b903b50ea0
https://gist.github.com/h1ght/308128ebc54552979c1aeac1080f5e93
i hope all logs above got correct timestamps.
https://gist.github.com/h1ght/701b2460c7a08ad27fbd6f5d1a7248e1
