### ISSUE TITLE
Upgrade from V3 -> V4 broke traefik reverse proxy

### ISSUE THREAD

**Issue by katbyte** [Sonarr/Sonarr#6123]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I upgraded from V3 to V4  by changing the docker image.  The server  fine when i hit the ip/port directly but not via the reverse proxy anymore (traefik)

it is by hostname not url path, i have set the correct application url

the docs don't mention traefik but pass host header which it does by default. oddly it doesn't look like the router is being created anymore

### Expected Behavior

reverse proxy still functions after upgrade 

### Steps To Reproduce

change from v3 to v4 in docker compose, docker compose up -d, 

compose file below in addtional info

### Environment

```markdown
- OS: Linux version 6.1.0-13-amd64 (debian-kernel@lists.debian.org) (gcc-12 (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)
- Sonarr: 4.0.0.700 
- Docker Install: 24.0.6
- Using Reverse Proxy: traefik v3
- Browser: chrome 
- Database: default
```

### What branch are you running?

Develop

### Trace Logs?

      
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Sonarr: https://sonarr.tv/donate
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    998
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[Info] Bootstrap: Starting Sonarr - /app/sonarr/bin/Sonarr - Version 4.0.0.700 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
[Info] AppFolderInfo: Data directory is being overridden to [/config] 
[Info] MigrationController: *** Migrating data source=/config/sonarr.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] MigrationController: *** Migrating data source=/config/logs.db;cache size=-10000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Info] Microsoft.Hosting.Lifetime: Now listening on: http://[::]:8989 
[Info] Microsoft.Hosting.Lifetime: Application started. Press Ctrl+C to shut down. 
[Info] Microsoft.Hosting.Lifetime: Hosting environment: Production 
[Info] Microsoft.Hosting.Lifetime: Content root path: /app/sonarr/bin 
[ls.io-init] done.

### Anything else?

```
sonarr:
    image: linuxserver/sonarr:develop-4.0.0.700-ls586
    container_name: sonarr
    hostname: sonarr
    domainname: sonarr.local.domain
    restart: "always"
    networks:
      web:
    dns:
      - 10.101.101.100
    ports:
      - "8989:8989"
    volumes:
      - /home/docker/config/media/sonarr:/config
      - /mnt/data/video/tv:/tv
    environment:
      - TZ="America/Vancouver"
      - PUID=1000
      - PGID=998
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.rule=Host(`sonarr.local.domain.me`)
      - traefik.http.routers.sonarr.middlewares=allowlist-vlan@file,compression@file
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=le-dns
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      #- traefik.http.services.sonarr.loadbalancer.server.scheme=https
    healthcheck:
      test: curl --fail http://localhost:8989/api/system/status?apikey=5a6d51e20d074d418408734a51d7a395 > /dev/null  || exit 1
      start_period: 300s
      interval: 30s
      timeout: 15s
      retries: 10
```

**Comment by markus101** [comment]
Please use one of the support channels: [forums](https://forums.sonarr.tv/), [subreddit](https://www.reddit.com/r/sonarr/), [discord ](https://discord.sonarr.tv/), or [IRC](https://web.libera.chat/?channels=#sonarr) for support/questions.

**Comment by owine** [comment]
Traefik will not setup the router until the container reports healthy. Try removing the healthcheck and then adding it back to see if it is working as expected.

**Comment by katbyte** [comment]
That was is @owine! thank you very much

for anyone else who ends up here it seems the api has changed, making my healthcheck

```
healthcheck:
      #test: curl --fail http://localhost:8989/api/system/status?apikey=> /dev/null  || exit 1
      test: curl --fail http://localhost:8989/ping > /dev/null  || exit 1
      start_period: 300s
      interval: 30s
      timeout: 15s
      retries: 10
```

fixed it
