### ISSUE TITLE
Sonarr not connecting to other services (Prowlarr, NZBget, qbittorrent etc)

### ISSUE THREAD

**Issue by jcourt** [Sonarr/Sonarr#6162]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Preface
My set up is all based on a Synology NAS. I have the Container Manager (docker) package running with a few active projects. Lidarr, Radarr, Bazarr, Sonarr, Overseerr, and Prowlarr are all separate containers and all share a project, local network, and yaml config file. NZBget is running in it's own container on a separate local network. I also have qbittorrent running as a container in a project with gluetun as it's network interface. Reverse proxy is managed by the Synology settings (built in).

Sonarr to qbittorrent
Reverse proxy (https://qbit.domain.com:443) is not accepted (Unable to connect to qBittorrent). Only the local IP (172.20.0.2) can be used without SSL. Radarr and Lidarr connect correctly using the reverse proxy and SSL.

Sonarr to Prowlarr
Adding Sonarr's reverse proxy (https://sonarr.domain.com:443) works, but adding Prowlarr's reverse proxy "the way Sonarr sees it" (https://prowlarr.domain.com:443) fails (Prowlarr URL is invalid, Sonarr cannot connect to Prowlarr). Prowlarr's local IP (172.20.0.2) must be used to connect. Radarr and Lidarr connect correctly using the reverse proxy and SSL.

Sonarr to NZBget
Neither the reverse proxy (https://nzbget.domain.com:443) nor the local IP (172.20.0.2) can be used. Both result in an authentication error. Radarr and Lidarr are not affected by this, and connect to NZBget correctly using the reverse proxy.

Sonarr to Bazarr
Sonarr connects currently to Bazarr using reverse proxy and SSL

Sonarr to Overseerr
Both Radarr and Sonarr connect properly to Overseerr via reverse proxy and SSL

Other services
Lidarr and Radarr connect to all other services correctly using reverse proxy and SSL

### Expected Behavior

When connecting to qbittorrent
Add download client with reverse proxy (qbit.domain.com:443) and test successfully

When connecting with Prowlarr
Input Prowlarr's reverse proxy "the way Sonarr sees it", and test successfully

When connecting to NZBget
Add download client with reverse proxy (qbit.domain.com:443) and test successfully

### Steps To Reproduce

Sonarr to qbittorrent
1. Add Download client in Sonarr
2. Select qbitorrent
3. Fill in information
4. Click Test

Sonarr to Prowlarr
1. Add App in Prowlarr
2. Select Sonarr
3. Fill in information
4. Click Test

Sonarr to NZBget
1. Add Download client in Sonarr
2. Select qbitorrent
3. Fill in information
4. Click Test

### Environment

```markdown
- OS: Synology DSM 7.2-64570 Update 1
- Sonarr: 3.0.10.1567
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox 119.0.1 (64-bit)
- Database: Maria DB 10.11.2-1303
```

### What branch are you running?

Main

### Trace Logs?

[sonarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13312795/sonarr.trace.txt)
[prowlarr.trace.txt](https://github.com/Sonarr/Sonarr/files/13312802/prowlarr.trace.txt)
[sonarr.trace(nzbget).txt](https://github.com/Sonarr/Sonarr/files/13312824/sonarr.trace.nzbget.txt)

### Anything else?

nzbget project

```
services:
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
      - NZBGET_USER=fn5vkswmg #optional
      - NZBGET_PASS=ekb@4i!3P#x#53@2 #optional
    volumes:
      - /volume1/docker/nzbget:/config
      - /volume1/Plex/downloads/usenet:/downloads #optional
    ports:
      - 6789:6789
    restart: unless-stopped
```
vpn-project

```
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080 # port for qbittorrent
      - 6881:6881 # qbit Shadowsocks
      - 6881:6881/udp # qbit Shadowsocks
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - PUID=1026
      - PGID=100
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=123
      - OPENVPN_PASSWORD=123
      - VPN_PORT_FORWARDING=on
      - TZ=Canada/Mountain
      - HTTPPROXY=off #change to on if you wish to enable
      - SHADOWSOCKS=off #change to on if you wish to enable
      - FIREWALL_OUTBOUND_SUBNETS=172.17.0.0/16,192.168.0.0/24 #change this in line with your subnet see note on guide.
      - FIREWALL_VPN_INPUT_PORTS=8080,58846 #uncomment this line and change the port as per the note on the guide
    network_mode: bridge
    labels:
      - com.centurylinklabs.watchtower.enable=false
    security_opt:
      - no-new-privileges:true
    restart: always
   
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
      - WEBUI_PORT=8080
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/Plex/downloads:/data
      - /volume1/Plex/downloads/complete:/data/complete
      - /volume1/Plex/downloads/incomplete:/data/incomplete
      - /volume1/Plex/downloads/torrents:/data/torrents
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
```
arr_services

```
services:

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
    volumes:
      - /volume1/docker/projects/arr_services/bazarr/config:/config
      - /volume1/Plex/Movies:/data/movies #optional
      - /volume1/Plex/TV:/data/tv #optional
    ports:
      - 6767:6767
    network_mode: bridge
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
    volumes:
      - /volume1/docker/projects/arr_services/radarr/config:/config
      - /volume1/Plex/Movies:/data/movies #optional
      - /volume1/Plex/downloads/complete:/data/complete #optional
    ports:
      - 7878:7878
    network_mode: bridge
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
    volumes:
      - /volume1/docker/projects/arr_services/sonarr/config:/config
      - /volume1/Plex/TV:/data/tv #optional
      - /volume1/Plex/downloads/complete:/data/complete #optional
    ports:
      - 8989:8989
    network_mode: bridge
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
    volumes:
      - /volume1/docker/projects/arr_services/lidarr/config:/config
      - /volume1/Plex/Music:/data/music #optional
      - /volume1/Plex/downloads/complete:/data/complete #optional
    ports:
      - 8686:8686
    network_mode: bridge
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Canada/Mountain
    volumes:
      - /volume1/docker/projects/arr_services/prowlarr/config:/config
    ports:
      - 9696:9696
    network_mode: bridge
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Canada/Mountain
#      - PORT=5055 #optional
    ports:
      - 5055:5055
    network_mode: bridge
    volumes:
      - /volume1/docker/projects/arr_services/overseerr/config:/app/config
    restart: unless-stopped
```
![Sonarr adding qbit](https://github.com/Sonarr/Sonarr/assets/17757022/fc86297e-08ea-497c-a4bd-b5d98c84feff)
![Sonarr adding nzbget](https://github.com/Sonarr/Sonarr/assets/17757022/d9198bef-cd78-48db-96ad-f40f6d9d2d31)
![Radarr connected to nzbget](https://github.com/Sonarr/Sonarr/assets/17757022/6c3a6ab1-4611-4344-a5ec-0f1c41269dbd)
![Radarr connected to qbit](https://github.com/Sonarr/Sonarr/assets/17757022/8d0edd29-e4ac-4851-b3f3-1f410ca62ff9)
![Lidarr connected to nzbget](https://github.com/Sonarr/Sonarr/assets/17757022/1d02cb1d-a80a-4b10-9391-005106b4731b)
![Lidarr connected to qbit](https://github.com/Sonarr/Sonarr/assets/17757022/9e3e9ecd-ebed-4526-881a-1451abfb89dd)
![Prowlarr connected to Lidarr](https://github.com/Sonarr/Sonarr/assets/17757022/05dcf9ef-e2c2-40e3-a41f-029ba8e19fbf)
![Prowlarr connected to Radarr](https://github.com/Sonarr/Sonarr/assets/17757022/09723c98-6658-4eec-9829-8a9aed661ed6)
![Prowlarr not connected to Sonarr](https://github.com/Sonarr/Sonarr/assets/17757022/f1d003f5-d2a4-4092-9719-afa1c30c7cc9)
![Overseerr connected to Sonarr and Lidarr](https://github.com/Sonarr/Sonarr/assets/17757022/456759fb-a5dc-4eb4-9a3f-fe7255dc4d41)
![Bazarr connected to Sonarr](https://github.com/Sonarr/Sonarr/assets/17757022/932d9e75-9474-4ffd-bc59-8c4e4b183267)
![Bazarr connected to Radarr](https://github.com/Sonarr/Sonarr/assets/17757022/11534890-0a96-47dc-8508-ac95cb32358c)
![Reverse Proxy](https://github.com/Sonarr/Sonarr/assets/17757022/6e8e0afc-a724-41a0-ae2a-fff90cdc515e)
![Radarr reverse proxy](https://github.com/Sonarr/Sonarr/assets/17757022/00dca8dd-fb6e-4f55-a9d8-b1b7a3a93847)
![Sonarr reverse proxy](https://github.com/Sonarr/Sonarr/assets/17757022/88c43d72-01e5-498f-8f22-771b8263a8b0)
![Container Manager Projects](https://github.com/Sonarr/Sonarr/assets/17757022/6fc6f0ca-f10d-4491-98d5-8e869b869064)
