### ISSUE TITLE
Don't Re-test Providers (Indexers, Download Clients, Connections) that haven't changed when updated

### ISSUE THREAD

**Issue by Callum027** [Sonarr/Sonarr#6169]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

In Sonarr V4, the API was updated to obfuscate passwords and API keys so that they cannot be checked from the responses.

https://github.com/Sonarr/Sonarr/commit/570be882154e73f8ad1de5b16b957bcb964697fd

I think this is going a bit too far: forced authentication ensures that at the minimum a username and password is required for default installations, and the API key cannot be retrieved from `initialize.json` without authentication.

Making it impossible to check what password is set on resources not only makes it for difficult for application developers that use the Sonarr API, it also is a worse user experience for users using the UI, as they will not be able to check passwords and API keys configured in Sonarr to see if they are correct or not.

### Describe the solution you'd like

I'd like this change reverted, or at least some other way to ensure passwords and API keys are correct that:

* Can be done from the Sonarr API (no "manual" checking or modification of `config.xml` required).
* Does not involve sending connection tests to Sonarr every time, opening up the risk of users being blocked from services due to incorrect password attempts.

### Describe alternatives you've considered

One alternative that might be feasible is some kind of "idempotency check" API endpoint for each resource type that simply returns `true` or `false` if the provided metadata is "correct", i.e. the same as configured in the instance.

### Anything else?

I am the developer of Buildarr, an application that automates some of the work in configuration *Arr applications.

In Buildarr, you can define configuration and resource definitions, and it will update Sonarr instance to reflect that configuration:

```yaml
---
 
sonarr:
  hostname: localhost
  port: 8989
  protocol: http
  api_key: 1a2b3c4d5e1a2b3c4d5e1a2b3c4d5e1a
  settings:
    connect:
      definitions:
        Email:
          type: email
          enable: true
          server: smtp.example.com
          port: 465
          use_encryption: true
          username: admin@example.com
          password: <password>
          from_address: Sonarr <system@example.com>
          recipient_addresses:
            - Administrator <admin@example.com>
          notification_triggers:
            on_grab: true
            on_import: true
            on_upgrade: true
            on_series_delete: true
            on_episode_file_delete: true
            on_episode_file_delete_for_upgrade: true
            on_health_issue: true
            include_health_warnings: true
            on_application_update: true
```

I am currently updating Buildarr to work with Sonarr V4. Due to the above change, Buildarr will not be able to check these resources idempotently, and thus be forced to update the resource every time it runs. Every time this happens for a notification definition, it runs a connection test, sending the user nuisance alerts.

* Buildarr: https://buildarr.github.io
* Radarr plugin for Buildarr: https://buildarr.github.io/plugins/sonarr
