### ISSUE TITLE
Cached Memory rising over time

### ISSUE THREAD

**Issue by GuyKh** [Sonarr/Sonarr#7711]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

Running in Docker container, over time memory consumption raises.

The next image is Docker memory / cached memory reflection before and after `docker restart sonarr` action.

<img width="1200" alt="Image" src="https://github.com/user-attachments/assets/ad9b1b5c-2734-45bc-92a5-3a6fe6d89ef4" />

### Expected Behavior

Memory should be released (even if not immediately, but eventually).

### Steps To Reproduce

1. Run via docker (docker-compare config:)
```
  sonarr:
    image: linuxserver/sonarr:amd64-latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022 #optional
      - DOCKER_MODS=linuxserver/mods:radarr-striptracks
    volumes:
      - ${HOME}/docker/sonarr/config:/config
      - "/etc/localtime:/etc/localtime:ro"
      - /mnt/nas:/nas
    ports:
      - 8989:8989
    networks:
      - t2_proxy
    restart: unless-stopped
```

### Environment

```markdown
- OS: Ubuntu
- Sonarr: 4.0.13.2932
- Docker Install: Yes (`linuxserver/amd64`)
- Using Reverse Proxy: Yes (Traefik)
- Browser: N/A
- Database: Sqlite 3.48.0
```

### What branch are you running?

Main

### Trace Logs?

N/A
